package cmd

// import built-in strategies
import (
	_ "github.com/wanewang/bbgo/pkg/strategy/autoborrow"
	_ "github.com/wanewang/bbgo/pkg/strategy/bollgrid"
	_ "github.com/wanewang/bbgo/pkg/strategy/bollmaker"
	_ "github.com/wanewang/bbgo/pkg/strategy/dca"
	_ "github.com/wanewang/bbgo/pkg/strategy/emastop"
	_ "github.com/wanewang/bbgo/pkg/strategy/etf"
	_ "github.com/wanewang/bbgo/pkg/strategy/ewoDgtrd"
	_ "github.com/wanewang/bbgo/pkg/strategy/factorzoo"
	_ "github.com/wanewang/bbgo/pkg/strategy/flashcrash"
	_ "github.com/wanewang/bbgo/pkg/strategy/fmaker"
	_ "github.com/wanewang/bbgo/pkg/strategy/funding"
	_ "github.com/wanewang/bbgo/pkg/strategy/grid"
	_ "github.com/wanewang/bbgo/pkg/strategy/kline"
	_ "github.com/wanewang/bbgo/pkg/strategy/marketcap"
	_ "github.com/wanewang/bbgo/pkg/strategy/pivotshort"
	_ "github.com/wanewang/bbgo/pkg/strategy/pricealert"
	_ "github.com/wanewang/bbgo/pkg/strategy/pricedrop"
	_ "github.com/wanewang/bbgo/pkg/strategy/rebalance"
	_ "github.com/wanewang/bbgo/pkg/strategy/rsmaker"
	_ "github.com/wanewang/bbgo/pkg/strategy/schedule"
	_ "github.com/wanewang/bbgo/pkg/strategy/skeleton"
	_ "github.com/wanewang/bbgo/pkg/strategy/supertrend"
	_ "github.com/wanewang/bbgo/pkg/strategy/support"
	_ "github.com/wanewang/bbgo/pkg/strategy/swing"
	_ "github.com/wanewang/bbgo/pkg/strategy/techsignal"
	_ "github.com/wanewang/bbgo/pkg/strategy/wall"
	_ "github.com/wanewang/bbgo/pkg/strategy/xbalance"
	_ "github.com/wanewang/bbgo/pkg/strategy/xgap"
	_ "github.com/wanewang/bbgo/pkg/strategy/xmaker"
	_ "github.com/wanewang/bbgo/pkg/strategy/xnav"
	_ "github.com/wanewang/bbgo/pkg/strategy/xpuremaker"
)
